/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    ACheckboxGroup: (typeof import('ant-design-vue/es'))['CheckboxGroup']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    ARadio: (typeof import('ant-design-vue/es'))['Radio']
    ARadioGroup: (typeof import('ant-design-vue/es'))['RadioGroup']
    ASelect: (typeof import('ant-design-vue/es'))['Select']
    ASelectOption: (typeof import('ant-design-vue/es'))['SelectOption']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
